[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
torix_program = "torXFavtJnaJzW7fz2NVrg9f1j824GitYi69zhmJQBK"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --nocapture && cp target/idl/torix_program.json ./idl/torix_program.json && NODE_OPTIONS='--no-experimental-strip-types' yarn ts-mocha -p tsconfig.json tests/**/*.test.ts --timeout 120000"

[test]
startup_wait = 5000

[[test.validator.clone]]
url = "https://api.mainnet-beta.solana.com"
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[hooks]
